# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Camelot' do
pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git'
end

target 'CamelotTests' do

end

